#!/bin/bash

if [ $# -ne 1 ]
then
    echo "ERROR: please supply version parameter, e.g. 1.5.1"
    exit 1
fi
version="$1"

ln -s . jouno-$version
tar --files-from=- -cvzf  /home/michael/rpmbuild/SOURCES/jouno-$version.tar.gz <<EOF
jouno-$version/.gitignore
jouno-$version/LICENSE.md
jouno-$version/README.md
jouno-$version/screen-shots/Screenshot_Large.png
jouno-$version/jouno.py
jouno-$version/jouno.png
EOF
echo /home/michael/rpmbuild/SOURCES/jouno-$version.tar.gz
rm jouno-$version
